In [61]:
import pandas as pd
import numpy as np
#dataset Extraction
dataset= pd.read_csv("winequality-red.csv")
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [62]:
#Feature Extractions and Partitions
X=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

In [63]:
#Test Train Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=5)


In [64]:
#data shape
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1279, 11)
(320, 11)
(1279, 1)
(320, 1)


In [65]:
#Linear Regression Modelling
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [66]:
#Combining into Frames for Attrib and Coeff
v =pd.DataFrame(regressor.coef_,index=['Co-efficient']).transpose()
w = pd.DataFrame(X.columns,columns=['Attributte'])


In [67]:
coeff_df = pd.concat([w,v],axis=1,join='inner')
coeff_df

Attributte  Co-efficient
0          fixed acidity      0.031645
1       volatile acidity     -1.132970
2            citric acid     -0.129163
3         residual sugar      0.029850
4              chlorides     -1.949411
5    free sulfur dioxide      0.002850
6   total sulfur dioxide     -0.002851
7                density    -21.014442
8                     pH     -0.377024
9              sulphates      0.904018
10               alcohol      0.253185

In [68]:
#Multiple Regression Predictions
y_pred = regressor.predict(X_test)
y_pred = pd.DataFrame(y_pred,columns=['Predicted'])
y_pred

Predicted
0     5.041118
1     5.667404
2     5.082331
3     6.470107
4     5.284082
5     4.955175
6     5.150530
7     6.425561
8     5.828029
9     5.288575
10    6.303365
11    5.078615
12    5.092691
13    5.862256
14    5.800087
15    5.606024
16    6.365051
17    5.852458
18    5.905202
19    5.658399
20    5.069823
21    5.331597
22    5.130531
23    5.232094
24    6.170009
25    5.297989
26    5.271628
27    5.412939
28    5.965369
29    6.512367
..         ...
290   5.440057
291   5.417020
292   6.330363
293   5.235872
294   5.271356
295   6.136987
296   5.975464
297   5.809231
298   5.283720
299   5.271628
300   5.702230
301   5.025286
302   5.897113
303   5.325010
304   5.250345
305   6.230190
306   5.497801
307   5.260389
308   5.107784
309   5.480539
310   5.976220
311   5.737514
312   5.188616
313   5.560069
314   4.944008
315   6.273601
316   5.198566
317   5.439915
318   4.838829
319   5.095718

[320 rows x 1 columns]

In [69]:
y_test

quality
236         6
833         4
424         5
982         6
1155        5
412         5
419         5
1098        7
1414        5
994         5
1066        7
189         5
1553        5
344         6
1377        6
292         6
970         6
489         6
230         7
906         5
123         5
961         5
1203        5
70          6
1021        6
386         6
141         5
51          6
346         7
1412        6
...       ...
786         5
1434        6
559         6
1387        5
573         4
1179        6
446         5
831         6
718         5
136         5
798         6
98          5
390         8
962         5
461         5
1323        7
534         6
370         5
769         5
634         5
527         6
1031        7
2           5
902         7
710         5
935         6
1500        5
748         6
1373        5
187         5

[320 rows x 1 columns]

In [70]:
#Metrics
from sklearn import metrics
print('Mean Absolute Error:',metrics.mean_absolute_error(y_test,y_pred))
print('Mean Squared error:',metrics.mean_squared_error(y_test,y_pred))
print('RMSE:',np.sqrt(metrics.mean_squared_error(y_test,y_pred)))
r2 = r2_score(y_test,y_pred)
print('R-Squared:',r2)

Mean Absolute Error: 0.4884665113567678
Mean Squared error: 0.4031775045635433
RMSE: 0.6349626009172062
R-Squared: 0.3787468743163519


In [71]:
#Ridge Rigression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

alpha = [1e-15, 1e-10, 1e-8, 1e-4, 1e-3,1e-2, 1, 5, 10, 20]
ridge = Ridge()
parameters = {'alpha': [1e-15, 1e-10, 1e-8, 1e-4, 1e-3,1e-2, 1, 5, 10, 20]}
ridge_reg = GridSearchCV(ridge, parameters,scoring='neg_mean_squared_error', cv=5)

#ridge_reg = Ridge(alpha=0.01, solver="cholesky")
ridge_reg.fit(X_train, y_train)
#ridge_reg.score(X_train, y_train)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.0001, 0.001, 0.01, 1, 5, 10, 20]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_squared_error', verbose=0)

In [72]:
#best parameter
ridge_reg.best_params_

{'alpha': 0.01}

In [73]:
ridge_reg.best_score_

-0.43228630584079486

In [74]:
#Ridge Predictions
y_ridge_pred = ridge_reg.predict(X_test)
y_ridge_pred = pd.DataFrame(y_ridge_pred,columns=['Predicted'])
y_ridge_pred

Predicted
0     5.035902
1     5.627455
2     5.078358
3     6.486049
4     5.281314
5     4.958988
6     5.161107
7     6.422305
8     5.846897
9     5.310231
10    6.303115
11    5.085407
12    5.103903
13    5.890675
14    5.826202
15    5.625805
16    6.347401
17    5.859322
18    5.901407
19    5.670790
20    5.063651
21    5.329817
22    5.113603
23    5.233263
24    6.153297
25    5.305132
26    5.263082
27    5.399091
28    5.970312
29    6.520485
..         ...
290   5.440062
291   5.396982
292   6.376639
293   5.232485
294   5.269304
295   6.137829
296   5.978000
297   5.784361
298   5.303511
299   5.263082
300   5.723551
301   5.016793
302   5.881840
303   5.330211
304   5.263032
305   6.209270
306   5.528207
307   5.264801
308   5.096997
309   5.481370
310   6.000068
311   5.740090
312   5.195127
313   5.569515
314   4.947959
315   6.260130
316   5.181048
317   5.444756
318   4.827414
319   5.104767

[320 rows x 1 columns]

In [75]:
#Metrics
from sklearn import metrics
rmse = np.sqrt(mean_squared_error(y_test,y_ridge_pred))
print('MAE:', metrics.mean_absolute_error(y_test,y_ridge_pred))
print('MSE:', metrics.mean_squared_error(y_test,y_ridge_pred))
print('RMSE:',rmse)
r2 = r2_score(y_test,y_ridge_pred)
print('R-Squared:',r2)

MAE: 0.48913343438517
MSE: 0.4029566436897859
RMSE: 0.6347886606499724
R-Squared: 0.3790871971434192


In [76]:
#Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
parameters = {'alpha': [1e-15, 1e-10, 1e-8, 1e-4, 1e-3,1e-2, 1, 5, 10, 20]}
lasso=Lasso()
lassoReg = GridSearchCV(lasso, parameters, scoring='neg_mean_squared_error', cv = 5)
#lassoReg = Lasso(alpha=0.0001,normalize=True)
lassoReg.fit(X_train,y_train)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.0001, 0.001, 0.01, 1, 5, 10, 20]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_squared_error', verbose=0)

In [77]:
#best parameter
lassoReg.best_params_

{'alpha': 0.0001}

In [78]:
lassoReg.best_score_

-0.43219848939866934

In [79]:
#Lasso Predictions
y_lasso_pred = lassoReg.predict(X_test)
y_lasso_pred = pd.DataFrame(y_lasso_pred,columns=['Predicted'])
y_lasso_pred

Predicted
0     5.035223
1     5.629215
2     5.079038
3     6.486299
4     5.281663
5     4.958746
6     5.162905
7     6.425998
8     5.847238
9     5.313671
10    6.301023
11    5.085547
12    5.104189
13    5.891732
14    5.832833
15    5.626956
16    6.344844
17    5.859338
18    5.900456
19    5.671686
20    5.063709
21    5.327539
22    5.112356
23    5.232560
24    6.157092
25    5.305935
26    5.259876
27    5.395934
28    5.969526
29    6.515135
..         ...
290   5.441062
291   5.398415
292   6.382481
293   5.231781
294   5.271406
295   6.135373
296   5.978351
297   5.781848
298   5.303906
299   5.259876
300   5.726239
301   5.016299
302   5.878912
303   5.329947
304   5.263121
305   6.204270
306   5.531818
307   5.264515
308   5.095935
309   5.480604
310   6.003525
311   5.739691
312   5.193878
313   5.571636
314   4.948559
315   6.258973
316   5.178105
317   5.445041
318   4.828962
319   5.106464

[320 rows x 1 columns]

In [80]:
#Metrics
from sklearn import metrics 
rmse = np.sqrt(mean_squared_error(y_test,y_lasso_pred))
print('MAE:', metrics.mean_absolute_error(y_test,y_lasso_pred))
print('MSE:', metrics.mean_squared_error(y_test,y_lasso_pred))
print('RMSE:',rmse)
r2 = r2_score(y_test,y_lasso_pred)
print('R-Squared:',r2)

MAE: 0.48912002382064673
MSE: 0.402967574363971
RMSE: 0.6347972702871137
R-Squared: 0.37907035415137114


In [91]:
#Elastic Net
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV

parameters = {'alpha': [1e-15, 1e-10, 1e-8, 1e-4, 1e-3,1e-2, 1, 5, 10, 20],'l1_ratio':[0.1]}
elasticNet=ElasticNet()
elasNetReg = GridSearchCV(elasticNet, parameters, scoring='neg_mean_squared_error', cv = 5)

# Fit/train LASSO
elasNetReg.fit(X_train,y_train)
# Predict
y_elasNetPred = elasNetReg.predict(X_test)

C:\Users\Ankur\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\Ankur\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\Ankur\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\Ankur\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increa

In [85]:
#best parameter
elasNetReg.best_params_

{'alpha': 0.0001, 'l1_ratio': 0.1}

In [90]:
#Metrics
from sklearn import metrics 
rmse = np.sqrt(mean_squared_error(y_test,y_elasNetPred))
print('MAE:', metrics.mean_absolute_error(y_test,y_elasNetPred))
print('MSE:', metrics.mean_squared_error(y_test,y_elasNetPred))
print('RMSE:',rmse)
r2 = r2_score(y_test,y_elasNetPred)
print('R-Squared:',r2)

MAE: 0.48902902594038694
MSE: 0.40286604561785466
RMSE: 0.6347172958237822
R-Squared: 0.37922679901785694


In [162]:
#decisiontree Regression
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0 , max_depth=3)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=3, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [163]:
y_dtr_pred = regressor.predict(X_test)
y_dtr_pred = pd.DataFrame(y_dtr_pred,columns=['Predicted'])
y_dtr_pred


Predicted
0     5.340909
1     6.297297
2     5.736842
3     6.631579
4     5.049451
5     5.522267
6     5.522267
7     6.631579
8     5.522267
9     5.049451
10    6.631579
11    5.340909
12    5.340909
13    6.098266
14    5.736842
15    5.522267
16    6.098266
17    5.522267
18    5.736842
19    6.098266
20    5.049451
21    5.340909
22    5.340909
23    5.340909
24    5.736842
25    5.522267
26    5.522267
27    5.340909
28    6.631579
29    6.098266
..         ...
290   5.049451
291   5.522267
292   6.631579
293   5.340909
294   5.340909
295   6.098266
296   6.297297
297   6.098266
298   5.049451
299   5.522267
300   5.736842
301   5.340909
302   6.631579
303   5.522267
304   5.340909
305   6.098266
306   5.340909
307   5.522267
308   5.340909
309   5.340909
310   6.098266
311   5.736842
312   5.522267
313   6.098266
314   5.340909
315   6.631579
316   5.049451
317   5.522267
318   5.049451
319   5.049451

[320 rows x 1 columns]

In [164]:
#Metrics
from sklearn import metrics 
rmse = np.sqrt(mean_squared_error(y_test,y_dtr_pred))
print('MAE:', metrics.mean_absolute_error(y_test,y_dtr_pred))
print('MSE:', metrics.mean_squared_error(y_test,y_dtr_pred))
print('RMSE:',rmse)
r2 = r2_score(y_test,y_dtr_pred)
print('R-Squared:',r2)

MAE: 0.5122756870798397
MSE: 0.4505191945617562
RMSE: 0.6712072664697218
R-Squared: 0.30579842715937344


In [177]:
#Polynmial Regression
#Doesnt work how we want it to.
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly_features.fit_transform(X_train)
poly_reg = LinearRegression()
poly_reg.fit(X_poly, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [193]:
y_poly_predicted = poly_reg.predict(X_poly)

In [180]:
from sklearn.metrics import mean_squared_error

poly_mse = mean_squared_error(y_train, y_poly_predicted)
poly_rmse = np.sqrt(poly_mse)
poly_rmse

0.6086953286747786

In [197]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(X_poly)
print(y_poly_predicted)

(1279, 11)
(320, 11)
(1279, 1)
(320, 1)
[[7.7000e+00 7.1500e-01 1.0000e-02 ... 3.2490e-01 6.7260e+00 1.3924e+02]
 [1.1200e+01 2.8000e-01 5.6000e-01 ... 3.3640e-01 5.6840e+00 9.6040e+01]
 [4.6000e+00 5.2000e-01 1.5000e-01 ... 3.1360e-01 7.3360e+00 1.7161e+02]
 ...
 [8.9000e+00 8.4000e-01 3.4000e-01 ... 2.3040e-01 4.3680e+00 8.2810e+01]
 [1.2800e+01 3.0000e-01 7.4000e-01 ... 5.9290e-01 8.3160e+00 1.1664e+02]
 [6.9000e+00 5.1000e-01 2.3000e-01 ... 7.0560e-01 9.4080e+00 1.2544e+02]]
[[5.79429015]
 [5.50663788]
 [5.1600668 ]
 ...
 [4.77003973]
 [6.02486154]
 [6.26781313]]


In [181]:
#Metrics
from sklearn import metrics 
rmse = np.sqrt(mean_squared_error(y_train,y_poly_predicted))
print('MAE:', metrics.mean_absolute_error(y_train,y_poly_predicted))
print('MSE:', metrics.mean_squared_error(y_train,y_poly_predicted))
print('RMSE:',rmse)
r2 = r2_score(y_train,y_poly_predicted)
print('R-Squared:',r2)

MAE: 0.4769258670528149
MSE: 0.3705100031504967
RMSE: 0.6086953286747786
R-Squared: 0.4321258813651271


In [207]:
#Knn regression
#k=5
from sklearn import neighbors
knn=neighbors.KNeighborsRegressor(5,weights='distance')
knn.fit(X_train,y_train)
y1_knn=knn.predict(X_train)

In [208]:
y2_knn=knn.predict(X_test)
y2_knn

array([[6.        ],
       [5.04464766],
       [5.        ],
       [5.85659385],
       [5.        ],
       [5.42217017],
       [5.95601467],
       [5.81426207],
       [5.38693191],
       [5.3721685 ],
       [5.58182544],
       [5.        ],
       [5.38443099],
       [5.19230718],
       [5.20920465],
       [5.63164102],
       [6.        ],
       [5.67597303],
       [5.50463406],
       [5.40624216],
       [5.60229208],
       [5.61004931],
       [6.        ],
       [5.51298479],
       [6.        ],
       [5.47989312],
       [5.94078258],
       [5.52964015],
       [6.40880768],
       [6.        ],
       [5.16704995],
       [5.        ],
       [5.15973121],
       [5.36973356],
       [5.7151644 ],
       [5.86886191],
       [6.03091115],
       [5.65945215],
       [5.29810563],
       [5.        ],
       [5.83035681],
       [5.        ],
       [6.        ],
       [5.2959523 ],
       [5.78301509],
       [6.        ],
       [5.        ],
       [6.   

In [209]:
#Metrics
from sklearn import metrics 
rmse = np.sqrt(mean_squared_error(y_test,y2_knn))
print('MAE:', metrics.mean_absolute_error(y_test,y2_knn))
print('MSE:', metrics.mean_squared_error(y_test,y2_knn))
print('RMSE:',rmse)
r2 = r2_score(y_test,y2_knn)
print('R-Squared:',r2)

MAE: 0.45062232457199514
MSE: 0.44009926893426476
RMSE: 0.6633997806257286
R-Squared: 0.3218544106708493


In [ ]:
#Random Forest Rgressor
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
#regressor.fit(X_train,y_train)